default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: snapscan_development

test:
  <<: *default
  database: snapscan_test
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
